url: https://y7kim.github.io

# Site settings
title: Twig Technology
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Team names, titles and social links
people:
  - name: Vismantas Dilys
    pic: 1
    position: Machine learning
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/vismantas/?original_referer=https%3A%2F%2Fwww%2Egoogle%2Elt%2F&originalSubdomain=lt

  - name: Vytautas Šeibutas
    pic: 2
    position: Experienced Solution Architect with expertise in system integration. Has 7 years of experience designing and evaluating student assessments to analyze and improve their sensitivity and efficiency.
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/vytautas-seibutas-6a56b1124/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
